# Generated by Django 4.2.16 on 2024-10-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest_service', '0002_initial'),
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(limit_choices_to={'role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, to='user_service.customuser'),
        ),
    ]
